name 'magmax-sentry'
version '2.0.10'

author 'Miguel Ángel García'
license 'Apache2'
project_page ''
source 'https://github.com/magmax/puppet-sentry'
summary 'Puppet module for sentry'
description 'This module installs and manages standard42. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
